// Code generated by goctl. DO NOT EDIT.
package types

type FileUploadReply struct {
	Identity string `json:"identity"`
	Ext      string `json:"ext"`
	Name     string `json:"name"`
}

type FileUploadRequest struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path"`
}

type LoginReply struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type MailCodeSendReply struct {
}

type MailCodeSendRequest struct {
	Email string `json:"email"`
}

type ShareBasicDetailReply struct {
}

type ShareBasicDetailRequest struct {
}

type UserDetailReply struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserRegisterReply struct {
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}
